name: deploy

on:
  push:
    branches:
      - main

jobs:
  caprover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u gleich --password-stdin
          docker build -t ghcr.io/gleich/lcp .
          docker push ghcr.io/gleich/lcp
      - run: "curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'"
