name: deploy

on:
  push:
    branches:
      - main

jobs:
  caprover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u gleich --password-stdin
          docker build -t ghcr.io/gleich/lcp .
          docker push ghcr.io/gleich/lcp
      - run: docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl https://api.mattglei.ch --caproverPassword ${{ secrets.CAPROVER_PASSWORD }} --caproverApp lcp --imageName ghcr.io/gleich/lcp
